version: '3.7'
services:

    peon-telegram:
        build:
            context: .
            dockerfile: ./Dockerfile_telegram
        # depends_on:
            # - mongodb-server
        env_file:
            - .env
            - .db.env
        volumes:
            - ./tools:/tools

    peon-discord:
        build:
            context: .
            dockerfile: ./Dockerfile_discord
        # depends_on:
            # - mongodb-server
        env_file:
            - .env
            - .db.env
        volumes:
            - ./tools:/tools

    # mongodb-server:
    #     image: mongo:4.2.0
    #     container_name: mongodb-server
    #     env_file:
    #         - .db.env
    #     volumes:
    #         - ./db/data:/data/db
    #     ports:
    #         - '27017:27017'
