version: '3'
services:

    peon:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        env_file:
            - .env
            - .db.env

    db:
        image: mongo:3.6
        container_name: peon-db
        env_file:
            - .db.env
        volumes:
            - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./db/data:/data/db
        ports:
            - '27017:27017'
