FROM python:3.9.14-alpine3.15

WORKDIR /tests

COPY ./requirements.txt /tests
COPY ./requirements-repos.txt /tests

RUN set -eux; \
    apk update; \
    apk add --no-cache bash git wget openssh-client; \
    mkdir -m 700 -p packages; \
    cd ./packages; \
    for link in $(cat /tests/requirements-repos.txt); do \
        git clone $link --no-tags ; \
    done;

RUN set -eux; \
    pip install --upgrade pip; \
    pip install --trusted-host pypi.python.org -r requirements.txt; \
    pip install packages/*; \
    pip install pytest ; \
    rm -rf packages;

COPY ./tests ./tests/
COPY ./common/assets/ /tests/assets
COPY ./common/peon_common /usr/local/lib/python3.9/site-packages/peon_common

CMD ["/usr/local/bin/pytest", "tests"]
