FROM python:3.9.14-alpine3.15

WORKDIR /app

COPY ./requirements.txt /app
COPY ./requirements-repos.txt /app

RUN set -eux; \
    apk update; \
    apk add --no-cache bash git wget openssh-client; \
    mkdir -m 700 -p packages; \
    cd ./packages; \
    for link in $(cat /app/requirements-repos.txt); do \
        git clone $link --no-tags ; \
    done;

RUN set -eux; \
    pip install --upgrade pip; \
    pip install --trusted-host pypi.python.org -r requirements.txt; \
    pip install packages/*; \
    rm -rf packages;

EXPOSE 80 443

COPY ./common/init/ /app/init
COPY ./common/assets/ /app/assets
COPY ./common/peon_common /usr/local/lib/python3.9/site-packages/peon_common
COPY ./telegram/start.py /app/init
COPY ./telegram/peon_telegram /usr/local/lib/python3.9/site-packages/peon_telegram

CMD ["/bin/bash", "./init/entrypoint.sh"]
