version: '3.7'
services:

    peon-telegram:
        build:
            context: ./
            dockerfile: ./peon_telegram/Dockerfile
            args:
                - timezone=${timezone}
        depends_on:
            - mongodb
        networks:
            - docker_network
        env_file:
            - .env
            - .db.env

    peon-discord:
        build:
            context: ./
            dockerfile: ./peon_discord/Dockerfile
            args:
                - timezone=${timezone}
        depends_on:
            - mongodb
        networks:
            - docker_network
        env_file:
            - .env
            - .db.env
        volumes:
            - ./peon_common/assets:/app/assets

    mongodb:
        image: mongo:4.2.0
        container_name: mongodb
        networks:
            - docker_network
        env_file:
            - .db.env
        volumes:
            - ./db/data:/data/db

networks:
  docker_network:
