services:

    peon-telegram:
        build:
            context: ./
            dockerfile: ./peon_telegram/Dockerfile
            args:
                - timezone=${timezone}
        depends_on:
            - mongodb
        networks:
            net1:
                ipv4_address: 172.29.1.12
        env_file:
            - .env
            - .db.env

    peon-discord:
        build:
            context: ./
            dockerfile: ./peon_discord/Dockerfile
            args:
                - timezone=${timezone}
        depends_on:
            - mongodb
        networks:
            net1:
                ipv4_address: 172.29.1.11
        env_file:
            - .env
            - .db.env
        volumes:
            - ./peon_common/assets:/app/assets

    mongodb:
        image: mongo:4.2.0
        container_name: mongodb
        networks:
            net1:
                ipv4_address: 172.29.1.10
        env_file:
            - .db.env
        volumes:
            - ./db/data:/data/db

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.1.0/24
