version: '3.7'
services:

    peon:
        build:
            context: .
            dockerfile: ./Dockerfile
        depends_on:
            - mongodb-server
        env_file:
            - .env
            - .db.env

    mongodb-server:
        image: mongo:4.2.0
        container_name: mongodb-server
        env_file:
            - .db.env
        volumes:
            - ./db/data:/data/db
        ports:
            - '27017:27017'
